Добавил разметку главной страницы
htmlacademy-adaptive/1859627-sedona-27 pull request #2
Opened 2022-11-28 15:46 UTC by Panyatna

2022-11-29 14:22 UTC, Mielilon reviewed
Важно проработать каждое замечание, потому что темы, которые они затрагивают, являются основополагающими

2022-11-29 14:22 UTC, mielilon commented on source/index.html
> +                  <li class="site-list__item site-list__item--current">
Класс .site-list__item--current не нужен в данном контексте, поэтому его нужно убрать. Все элементы .site-list__item являются исходными, без модификаций. Для демонстрации состояния, можно добавить модификатор активности к оному из элементов. Этого будет достаточно.

2022-11-29 14:22 UTC, mielilon commented on source/index.html
> +            <svg width="282" height="214" viewBox="0 0 282 214" fill="none" xmlns="http://www.w3.org/2000/svg">
В силу того, что мы никак не будем взаимодействовать с svg (изменять цвет, положение элементов), нам нужно добавить его как картинку. Иначе код сильно разрастается.

2022-11-29 14:22 UTC, Mielilon commented on source/index.html
> +            <nav class="main-nav">
Соответственно, тут тоже приставка main не нужна. Можно поставить класс navigation

2022-11-29 14:22 UTC, Mielilon commented on source/index.html
> +            <a class="main-header__logo">
logo помимо элемента также является отдельным блоком, который можно независимо переиспользовать. Нужно это учесть в именовании.

2022-11-29 14:22 UTC, Mielilon commented on source/index.html
> +              <button class="main-nav__toggle" type="button">
Кнопку нужно вынести из навигации на уровень выше

2022-11-29 14:22 UTC, Mielilon commented on source/index.html
> +              <div class="main-nav__wrapper">
Для чего нужна эта обертка, если уже есть тег nav? Лучше будет ее убрать.

2022-11-29 14:22 UTC, Mielilon commented on source/index.html
> +            <svg width="282" height="214" viewBox="0 0 282 214" fill="none" xmlns="http://www.w3.org/2000/svg">
svg никак не изменяется при взаимодействии, поэтому лучше вставить его через тег img. Также его нужно обернуть в тег, которому будет задан фон надписи

2022-11-29 14:22 UTC, Mielilon commented on source/index.html
> +            <span class="main-container__discription">Рассмотрим 5 причин, по которым Седона круче, чем гранд каньон!</span>
Этот, а так же блок с заголовком и изображением нужно обернуть в отдельную секцию со скрытым заголовком.

2022-11-29 14:22 UTC, Mielilon commented on source/index.html
> +                            <span class="advanteges__discription">— №1 —</span>
Тут опечатка. Правильно будет: description. Нужно поправить на всей странице

2022-11-29 14:22 UTC, Mielilon commented on source/index.html
> +                            <h3 class="advanteges__header advantages__item--housing">Жилье</h3>
Нужно поправить наименование модификатора, иначе теряется логика.

2022-11-29 14:22 UTC, Mielilon commented on source/index.html
> +                        <li class="advantages__item advantages__item--food">
Правильнее будет перенести модификатор к заголовку, ибо изображение будет добавляться на заголовок

2022-11-29 14:22 UTC, Mielilon commented on source/index.html
> +                          <h3 class="advanteges__header">Еда</h3>
Лучше назвать этот и схожие блоки как __title, вместо __header

2022-11-29 14:22 UTC, Mielilon commented on source/index.html
> +                            <span class="advanteges__discription">Не только китайского, но и местного производства!</span>
span-ы с текстом лучше заменить на параграфы (тег p)

2022-11-29 14:22 UTC, Mielilon commented on source/index.html
> +                          <span class="advanteges__discription">— №2 —</span>
Декоративные полоски будут добавлены за счет стилей, их нужно убрать из разметки

2022-11-29 14:22 UTC, Mielilon commented on source/index.html
> +                          <img class="advantages__img" src="#" alt="Красный каньон">
Изображение не нужно оборачивать в отдельный элемент списка, ибо оно относится к предыдущему. 

Также нужно изменить alt на более информативный. Например: alt="Фотография настоящего города" или alt="Фотография строений Седоны"

2022-11-29 14:22 UTC, Mielilon commented on source/index.html
> +            <section class="interesting">
Некорректное именование класса. Лучше ориентироваться на смысл. На макете представлена офферная конструкция, значит мы можем именовать ее как offer

2022-11-29 14:22 UTC, Mielilon commented on source/index.html
> +                <h2 class="visually_hidden">Местоположение седоны</h2>
Пробел в классах заменяется иначе, правильно: visually-hidden

2022-11-29 14:22 UTC, Mielilon commented on source/index.html
> +        <footer class="main-footer">
Аналогично header и nav можно убрать приставку main.

2022-11-29 14:22 UTC, Mielilon commented on source/index.html
> +            <div class="main-footer__wrapper">
Лишняя обертка

2022-11-29 14:22 UTC, Mielilon commented on source/index.html
> +                <div class="footer-hashtag">
hashtag может быть отдельным блоком, который имеет зависимый элемент. Важно это показать

2022-11-29 14:22 UTC, Mielilon commented on source/index.html
> +                <div class="footer-social">
social может быть отдельным блоком, который имеет зависимые элементы. Важно это показать

2022-11-29 14:22 UTC, Mielilon commented on source/index.html
> +                <div class="footer-copyright">
copyright может быть отдельным блоком, который имеет зависимые элементы. Важно это показать

2022-11-29 14:22 UTC, Mielilon commented on source/index.html
> +                    <svg width="27" height="35" viewBox="0 0 27 35" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M13.6 0h-.1L0 1.4v24.7l13.5 8 13.4-8V1.4L13.6 0ZM25 12.1 13.5 5.3v-.1h-.1l-
Лучше заменить на img

2022-12-01 17:02 UTC, Mielilon requested changes

2022-12-01 17:02 UTC, mielilon commented on source/index.html
> +                <div>
Можно сказать, что это превью к преимуществам, поэтому этот блок нужно перенести в секцию advantages.

2022-12-01 17:02 UTC, mielilon commented on source/index.html
> +                    <ul class="advantages__list">
Хоть это и похоже на список, но будет лучше обернуть в обычные дивы.

Из дизайна мы можем выделить секцию преимуществ и декомпозировать ее на следующие блоки:
1. Первое преимущество с изображением;
2. Рекомендации;
3. Второе преимущество;
4. Оставшиеся рекомендации.

2022-12-01 17:02 UTC, mielilon commented on source/index.html
> +                          <span class="advanteges__description">№5</span>
Нужно указать модификатор, чтобы появилась возможность добавить декор

2022-12-01 17:02 UTC, mielilon commented on source/index.html
> +                <a class="map__link" href="#"></a>
Ссылка тут не нужна, карту-заглушку мы добавим за счет фоновой картинки

2022-12-01 17:02 UTC, mielilon commented on source/index.html
> +            <div class="footer-hashtag hashtag">
Почти верно, однако элемент должен указываться через два нижних подчеркивания: footer__hashtag

2022-12-01 17:02 UTC, mielilon commented on source/index.html
> +            <div class="footer-social social">
Аналогично предыдущему пункту с footer__hashtag

2022-12-01 17:02 UTC, mielilon commented on source/index.html
> +            <div class="footer-copyright copyright">
Аналогично предыдущему пункту с footer__hashtag

2022-12-01 17:02 UTC, mielilon commented on source/index.html
> +                <img src="img/logo-htmlacademy.png" alt="Логотип разработчика сайта.">
Небольшая корректировка: в alt лучше не ставить точку в конце предложений

2022-12-05 16:38 UTC, Mielilon requested changes

2022-12-05 16:38 UTC, Mielilon commented on source/index.html
> +                <img src="img/map-desktop.jpg">
Этот блок можно удалить

2022-12-05 16:38 UTC, Mielilon commented on source/index.html
> +                        <div class="advantages__container">
Этот блок является списком из трех элементов advantages__item. Без выделения мы не сможем их полноценно декорировать и позиционировать

2022-12-05 16:38 UTC, Mielilon commented on source/index.html
> +                        <div class="advantages__container">
Этот блок является списком из трех элементов advantages__item. Без выделения мы не сможем их полноценно декорировать и позиционировать

2022-12-06 15:02 UTC, merged